#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

echo "Hello World!" > /var/www/html/index.html
replacement="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

ufw allow 'NGINX Full'

service nginx restart
