#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
if ! nginx -v; then
apt-get update
apt-get install -y nginx
fi

echo "Hello World!" > /var/www/html/index.html
str="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

# setting up 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="\\
\terror_page 404 /404.html;\\
\tlocation = /404.html {\\
\t\troot /var/www/html;\\
\t\tinternal;\\
\t}\\
\tadd_header X-Served-By $(hostname);"
sudo sed -i '/listen 80 default_server;/a '"$replacement"'' /etc/nginx/sites-enabled/default

ufw allow 'NGINX Full'
# restart the server
sudo service nginx restart
