#!/usr/bin/env bash
# A script that installs haproxy on a webserver
if ! haproxy -v
then
	sudo apt -y install software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
	sudo apt update
	sudo apt install haproxy -y
fi;

script="frontend http
	bind *:80
	mode http

	default_backend default_server

backend default_server
	balance roundrobin
	mode http
	server 348102-web-01 3.90.82.95:80 check
	server 348102-web-02 54.157.156.207:80 check
"

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "$script" | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart