#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.

# The script should only display:
# username
# user id
# Home directory path for the user

exec 3< /etc/passwd

while read -u 3 -r line;
do
	echo "$line" | cut -d ":" -f 1,3,6
done;
: 3<&-