#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

a="$(ls)"
for i in $a;
do
	echo "$i" | cut -d "-" -f 2
done;