#!/usr/bin/env bash
# cofigure a web server to have a firewall installed with only ports 22, 443 and 80 opened

sudo apt install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo sed disable
sudo sed enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
