#!/usr/bin/env bash
# A  Bash script that configures an Ubuntu server with the below requirements.

# Requirements:
  # localhost resolves to 127.0.0.2
  # facebook.com resolves to 8.8.8.8

echo "8.8.8.8 facebook.com" > /etc/hosts
echo "127.0.0.2     localhost" >> /etc/hosts
# sed -i "s/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/" /etc/hosts
